### ISSUE TITLE
"Can\'t set headers after they are sent."

### ISSUE THREAD

**Issue by ki9us** [qur2/express-crash#1]
Hi.  Not sure if you maintain this repo, but I have [an issue](https://github.com/Tracman-org/Server/issues/1): 

Code:

``` javascript
var handle404 = function(err,req,res,next) {
    if (err) { console.log('404 handling error: '+err); }
    res.render('error.html', {code:404});
};
var handle500 = function(err,req,res,next) {
    if (err) { console.log('500 handling error: '+err); }
    res.render('error.html', {code:500});
};
app.use(crash.handle404(handle404));
app.use(crash.handle500(handle500));
crash.trapRoute(app);
crash.handle(app, handle404, handle500);
```

Result:

```
404 handling error: NotFoundError: Not found error                                                                           
_http_outgoing.js:344                                                                                                        
    throw new Error('Can\'t set headers after they are sent.');                                                              
    ^                                                                                                                        

Error: Can't set headers after they are sent.                                                                                
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)                                                   
    at ServerResponse.header (/home/ubuntu/workspace/node_modules/express/lib/response.js:718:10)                            
    at ServerResponse.contentType (/home/ubuntu/workspace/node_modules/express/lib/response.js:551:15)                       
    at ServerResponse.send (/home/ubuntu/workspace/node_modules/express/lib/response.js:138:14)                              
    at res.render.done (/home/ubuntu/workspace/node_modules/express/lib/response.js:957:10)                                  
    at /home/ubuntu/workspace/node_modules/nunjucks/src/environment.js:22:23                                                 
    at RawTask.call (/home/ubuntu/workspace/node_modules/nunjucks/node_modules/asap/asap.js:40:19)                           
    at flush (/home/ubuntu/workspace/node_modules/nunjucks/node_modules/asap/raw.js:50:29)                                   
    at nextTickCallbackWith0Args (node.js:420:9)                                                                             
    at process._tickCallback (node.js:349:13) 
```

I think somehow `next()` is being called, and the `Can't set headers` error is thrown by [express's default error handler](http://expressjs.com/en/guide/error-handling.html#the-default-error-handler).  Or am I doing something wrong?

**Comment by qur2** [comment]
Hi,

I'm sorry you stumbled on an issue. As a matter of fact, I don't maintain this repo anymore. Also it was used along with express 3.1.x (should be a peerDependency, I know), and express 3 is deprecated now.

The best advice I can give is to not use `express-crash`.
If you're willing to use it anyway and fix the issues, I'll gladly accept PRs or transfer ownership of the repo.
